#!/usr/bin/env Rscript

suppressPackageStartupMessages({library(data.table);library(Matrix);library(limma);library(digest)})
args<-commandArgs(trailingOnly=TRUE);root<-if(length(args))normalizePath(args[1],winslash="/",mustWork=TRUE)else normalizePath(".",winslash="/");setwd(root);set.seed(20260810)
out<-"results/03_phase3";for(d in c("baseline","licensing","sender","qc","figures"))dir.create(file.path(out,d),recursive=TRUE,showWarnings=FALSE)
write_csv<-function(x,p)fwrite(x,p,na="",quote=TRUE)
universe<-fread(file.path(out,"ligand_universe/frozen_ligand_universe.csv"));donors<-fread(file.path(out,"metadata/hucmsc_donor_registry.csv"));strata_reg<-fread(file.path(out,"metadata/licensing_strata_registry.csv"));ligands<-universe$gene
stopifnot(nrow(universe)==1226,sum(donors$is_hucmsc_sender_donor=="YES")==8,all(strata_reg[valid_within_stratum_contrast=="YES",stratum_id]==c("Donor1_P5","Donor2_P2","Donor2_P5")))

find_one<-function(pattern){z<-list.files("data/raw/phase3",pattern=pattern,full.names=TRUE);stopifnot(length(z)==1);z}
read_10x_summary<-function(dataset,sample_id,donor_id,tissue,is_sender){
  message("Donor summary ",dataset," ",donor_id)
  feature_file<-find_one(paste0("^",sample_id,"_.*_(genes|features)\\.tsv\\.gz$"));matrix_file<-find_one(paste0("^",sample_id,"_.*_matrix\\.mtx\\.gz$"));barcode_file<-find_one(paste0("^",sample_id,"_.*_barcodes\\.tsv\\.gz$"))
  feat<-read.delim(gzfile(feature_file),header=FALSE,stringsAsFactors=FALSE);symbol<-as.character(feat[[2]]);m<-as(readMM(gzfile(matrix_file)),"dgCMatrix");stopifnot(nrow(m)==nrow(feat),ncol(m)==length(readLines(gzfile(barcode_file),warn=FALSE)))
  lib<-colSums(m);mapped<-which(symbol%in%ligands&!is.na(symbol)&symbol!="");map_i<-match(symbol[mapped],ligands)
  S<-sparseMatrix(i=map_i,j=mapped,x=1,dims=c(length(ligands),nrow(m)));lm<-S%*%m;measured<-seq_along(ligands)%in%map_i
  total<-sum(lib);cpm<-as.numeric(rowSums(lm))/total*1e6;frac<-as.numeric(rowSums(lm>0))/ncol(lm);mean_cp10k<-as.numeric(lm%*%(10000/pmax(lib,1)))/ncol(lm)
  cpm[!measured]<-NA_real_;frac[!measured]<-NA_real_;mean_cp10k[!measured]<-NA_real_;rankp<-rep(NA_real_,length(ligands));rankp[measured]<-(rank(cpm[measured],ties.method="average")-.5)/sum(measured)
  dt<-data.table(dataset=dataset,donor_id=donor_id,sample_id=sample_id,tissue_source=tissue,analysis_role=ifelse(is_sender,"CORE_BASELINE","SOURCE_CONTEXT_ONLY"),gene=ligands,gene_measured=ifelse(measured,"YES","NO"),pseudobulk_CPM=cpm,fraction_expressing_cells=frac,mean_cell_CP10K=mean_cp10k,within_donor_ligand_rank_percentile=rankp,donor_supported=ifelse(measured&cpm>=1&frac>=.10,"YES","NO"),donor_low_detected=ifelse(measured&cpm>=.1&frac>=.01,"YES","NO"),cells=ncol(m),total_counts=total,median_cell_library_size=median(lib),expression_layer="TRUE_CELLRANGER_RAW_COUNTS",biological_unit="DONOR",source_url=paste0("https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=",sample_id,"|results/03_phase3/ligand_universe/frozen_ligand_universe.csv"))
  qc<-data.table(dataset=dataset,donor_id=donor_id,tissue_source=tissue,is_sender_donor=ifelse(is_sender,"YES","NO"),cells=ncol(m),total_counts=total,median_library_size=median(lib),detected_all_gene_features=sum(rowSums(m)>0),source_url=paste0("https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=",sample_id))
  rm(m,lm,S);invisible(gc());list(expression=dt,qc=qc)
}

baseline_rows<-list();baseline_qc<-list();bidx<-donors[dataset%in%c("GSE182158","GSE199071")]
for(i in seq_len(nrow(bidx))){z<-read_10x_summary(bidx$dataset[i],bidx$sample_id[i],bidx$donor_id[i],bidx$tissue_source[i],bidx$is_hucmsc_sender_donor[i]=="YES");baseline_rows[[i]]<-z$expression;baseline_qc[[i]]<-z$qc}
baseline<-rbindlist(baseline_rows);bqc<-rbindlist(baseline_qc);setorder(baseline,gene,dataset,donor_id);write_csv(baseline,file.path(out,"baseline/baseline_ligand_expression_by_donor.csv"))

core<-baseline[analysis_role=="CORE_BASELINE"]
safe_median<-function(x){x<-x[is.finite(x)];if(length(x))median(x)else NA_real_}
safe_sd<-function(x){x<-x[is.finite(x)];if(length(x)>1)sd(x)else NA_real_}
safe_span<-function(x){x<-x[is.finite(x)];if(length(x)>1)diff(range(x))else 0}
safe_iqr<-function(x){x<-x[is.finite(x)];if(length(x)>1)IQR(x)else 0}
rob<-core[,{
  d182<-.SD[dataset=="GSE182158"];d199<-.SD[dataset=="GSE199071"]
  s182<-sum(d182$donor_supported=="YES");s199<-sum(d199$donor_supported=="YES");l182<-sum(d182$donor_low_detected=="YES");l199<-sum(d199$donor_low_detected=="YES")
  robust<-s182==2&s199>=3
  cls<-if(robust)"ROBUST_BASELINE_SENDER"else if(l182>=1&l199>=1)"MULTIDATASET_LOW_EXPRESSION"else if((s182>=2&l199==0)|(s199>=2&l182==0))"DATASET_SPECIFIC"else if((s182+s199)>=2)"DONOR_VARIABLE"else "NOT_RELIABLY_EXPRESSED"
  varflag<-(safe_span(d182$fraction_expressing_cells)>=.25)||(safe_span(d199$fraction_expressing_cells)>=.25)||(safe_iqr(d182$within_donor_ligand_rank_percentile)>=.20)||(safe_iqr(d199$within_donor_ligand_rank_percentile)>=.20)
  list(gse182_supported_donor_n=s182,gse199_supported_donor_n=s199,total_supported_donor_n=s182+s199,gse182_low_detected_donor_n=l182,gse199_low_detected_donor_n=l199,gse182_median_CPM=safe_median(d182$pseudobulk_CPM),gse199_median_CPM=safe_median(d199$pseudobulk_CPM),gse182_median_fraction=safe_median(d182$fraction_expressing_cells),gse199_median_fraction=safe_median(d199$fraction_expressing_cells),gse182_median_rank=safe_median(d182$within_donor_ligand_rank_percentile),gse199_median_rank=safe_median(d199$within_donor_ligand_rank_percentile),between_donor_log2cpm_sd=safe_sd(log2(.SD$pseudobulk_CPM+1)),donor_variable_flag=if(varflag)"YES"else "NO",baseline_classification=cls)
},by=gene]
ctx<-baseline[dataset=="GSE182158",.(uc_median_rank=safe_median(within_donor_ligand_rank_percentile[tissue_source=="Umbilical cord"]),non_uc_median_rank=safe_median(within_donor_ligand_rank_percentile[tissue_source!="Umbilical cord"])),by=gene]
ctx[,`:=`(uc_minus_non_uc_rank=uc_median_rank-non_uc_median_rank,source_context_flag=fcase(uc_median_rank-non_uc_median_rank>=.25,"UC_HIGHER_CONTEXT",uc_median_rank-non_uc_median_rank<=-.25,"UC_LOWER_CONTEXT",default="NO_LARGE_CONTEXT_SHIFT"))]
rob<-merge(rob,ctx,by="gene",all.x=TRUE);rob[,`:=`(robustness_rule="GSE182158 2/2 plus GSE199071 >=3/4 donor support; CPM>=1 and expressing fraction>=0.10",source_context_interpretation="DESCRIPTIVE_ONLY_NOT_CAUSAL_NOT_REQUIRED_FOR_ROBUSTNESS",source_url="results/03_phase3/baseline/baseline_ligand_expression_by_donor.csv|config/phase3_analysis.json")];setorder(rob,gene);write_csv(rob,file.path(out,"baseline/baseline_sender_robustness.csv"))

rho<-cor(rob$gse182_median_rank,rob$gse199_median_rank,method="spearman",use="complete.obs")
conc<-rob[,.(gene,gse182_median_rank,gse199_median_rank,rank_difference=gse182_median_rank-gse199_median_rank,rank_quartile_agreement=ifelse(abs(gse182_median_rank-gse199_median_rank)<=.25,"YES","NO"),overall_spearman_rho=rho,baseline_classification,source_url="results/03_phase3/baseline/baseline_ligand_expression_by_donor.csv")];write_csv(conc,file.path(out,"baseline/cross_dataset_sender_concordance.csv"))

# GSE117837 submitted raw read counts and exact cell alias crosswalk.
read_soft<-function(acc)readLines(gzfile(file.path("data/raw",paste0(acc,"_family.soft.gz")),encoding="UTF-8"),warn=FALSE)
blocks<-function(acc){z<-read_soft(acc);idx<-grep("^\\^SAMPLE = ",z);ends<-c(idx[-1]-1,length(z));lapply(seq_along(idx),function(i)z[idx[i]:ends[i]])}
field1<-function(b,p){z<-sub(p,"",grep(paste0("^",p),b,value=TRUE));if(length(z))z[1]else NA_character_};char1<-function(b,k){z<-sub("^!Sample_characteristics_ch1 = ","",grep("^!Sample_characteristics_ch1 = ",b,value=TRUE));v<-z[startsWith(tolower(z),paste0(tolower(k),":"))];if(length(v))trimws(sub("^[^:]+:","",v[1]))else NA_character_}
cellmap<-rbindlist(lapply(blocks("GSE117837"),function(b){title<-field1(b,"!Sample_title = ");alias<-sub(".*\\[([^]]+)\\].*","\\1",title);tr<-tolower(char1(b,"treatment"));data.table(alias=alias,sample_id=sub("^\\^SAMPLE = ","",b[1]),donor_id=char1(b,"donor id"),passage=paste0("P",char1(b,"passage")),condition=ifelse(grepl("stim|ifn|tnf",tr),"IFNG_TNFA_STIMULATED","UNTREATED"))}))
tab<-read.csv(gzfile("data/raw/phase3/GSE117837_Transcriptional_single_cell_analysis_of_hUC_MSCs.csv.gz"),check.names=FALSE,stringsAsFactors=FALSE);gene<-as.character(tab[[1]]);cnt<-as.matrix(tab[,-1,drop=FALSE]);storage.mode(cnt)<-"double";stopifnot(ncol(cnt)==361,setequal(colnames(cnt),cellmap$alias));cellmap<-cellmap[match(colnames(cnt),alias)];stopifnot(!anyNA(cellmap$donor_id));cnt<-rowsum(cnt,group=gene,reorder=TRUE);gene<-rownames(cnt)
calc_group<-function(d,p,cnd){idx<-which(cellmap$donor_id==d&cellmap$passage==p&cellmap$condition==cnd);stopifnot(length(idx)>0);x<-cnt[,idx,drop=FALSE];lib<-sum(x);list(cpm=rowSums(x)/lib*1e6,frac=rowMeans(x>0),cells=length(idx),library=lib)}
valid<-data.table(stratum_id=c("Donor1_P5","Donor2_P2","Donor2_P5"),donor_id=c("Donor1","Donor2","Donor2"),passage=c("P5","P2","P5"))
effects<-matrix(NA_real_,nrow=nrow(cnt),ncol=nrow(valid),dimnames=list(gene,valid$stratum_id));group_cache<-list();pass_rows<-list()
for(i in seq_len(nrow(valid))){u<-calc_group(valid$donor_id[i],valid$passage[i],"UNTREATED");s<-calc_group(valid$donor_id[i],valid$passage[i],"IFNG_TNFA_STIMULATED");e<-log2((s$cpm+.5)/(u$cpm+.5));effects[,i]<-e;group_cache[[valid$stratum_id[i]]]<-list(u=u,s=s,e=e);mi<-match(ligands,gene);pass_rows[[i]]<-data.table(dataset="GSE117837",stratum_id=valid$stratum_id[i],donor_id=valid$donor_id[i],passage=valid$passage[i],gene=ligands,gene_measured=ifelse(!is.na(mi),"YES","NO"),untreated_CPM=u$cpm[mi],stimulated_CPM=s$cpm[mi],untreated_fraction_cells=u$frac[mi],stimulated_fraction_cells=s$frac[mi],licensing_log2_effect=e[mi],effect_direction=fcase(e[mi]>=.5,"UP_GE_0.5",e[mi]<=-.5,"DOWN_LE_NEG_0.5",default="BELOW_MAGNITUDE_THRESHOLD"),untreated_cells=u$cells,stimulated_cells=s$cells,biological_unit="DONOR_PASSAGE_STRATUM_NOT_CELL",source_url="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE117837|config/phase3_analysis.json")}
pass_effect<-rbindlist(pass_rows);write_csv(pass_effect,file.path(out,"licensing/licensing_effect_by_donor_passage.csv"))

e1<-effects[,"Donor1_P5"];e2p2<-effects[,"Donor2_P2"];e2p5<-effects[,"Donor2_P5"];e2<-apply(cbind(e2p2,e2p5),1,median);donor_effects_all<-cbind(Donor1=e1,Donor2=e2);mean_effect<-rowMeans(donor_effects_all)
mi<-match(ligands,gene);drows<-rbindlist(list(data.table(gene=ligands,donor_id="Donor1",passages="P5",donor_level_log2_effect=e1[mi],passage_effect_min=e1[mi],passage_effect_max=e1[mi],passage_direction_consistent="NOT_APPLICABLE_ONE_PASSAGE"),data.table(gene=ligands,donor_id="Donor2",passages="P2;P5",donor_level_log2_effect=e2[mi],passage_effect_min=pmin(e2p2[mi],e2p5[mi]),passage_effect_max=pmax(e2p2[mi],e2p5[mi]),passage_direction_consistent=ifelse(sign(e2p2[mi])==sign(e2p5[mi]),"YES","NO"))))
drows[,`:=`(dataset="GSE117837",biological_unit="DONOR",aggregation_rule=ifelse(donor_id=="Donor2","median of P2 and P5 stratum effects","P5 stratum effect"),source_url="results/03_phase3/licensing/licensing_effect_by_donor_passage.csv|config/phase3_analysis.json")];setcolorder(drows,c("dataset","gene","donor_id","passages","donor_level_log2_effect","passage_effect_min","passage_effect_max","passage_direction_consistent","biological_unit","aggregation_rule","source_url"));write_csv(drows,file.path(out,"licensing/licensing_effect_by_donor.csv"))

retain<-vapply(seq_along(ligands),function(i){j<-mi[i];!is.na(j)&&all(vapply(group_cache,function(z)z$s$cpm[j]>=1,logical(1)))},logical(1));pdep<-!is.na(mi)&(((e2p2[mi]*e2p5[mi]<0)&pmax(abs(e2p2[mi]),abs(e2p5[mi]))>=.5)|abs(e2p2[mi]-e2p5[mi])>=1);ddep<-!pdep&!is.na(mi)&(e1[mi]*e2[mi]<0)&pmax(abs(e1[mi]),abs(e2[mi]))>=.5;up<-!pdep&!ddep&!is.na(mi)&e1[mi]>=.5&e2[mi]>=.5&e1[mi]>0&e2p2[mi]>0&e2p5[mi]>0;down<-!pdep&!ddep&!is.na(mi)&e1[mi]<=-.5&e2[mi]<=-.5&e1[mi]<0&e2p2[mi]<0&e2p5[mi]<0
lic<-data.table(gene=ligands,gene_measured=ifelse(!is.na(mi),"YES","NO"),donor1_effect=e1[mi],donor2_effect=e2[mi],donor2_p2_effect=e2p2[mi],donor2_p5_effect=e2p5[mi],median_donor_effect=apply(cbind(e1[mi],e2[mi]),1,median,na.rm=TRUE),absolute_median_donor_effect=apply(abs(cbind(e1[mi],e2[mi])),1,median,na.rm=TRUE),retained_after_stimulation_all_strata=ifelse(retain,"YES","NO"),licensing_classification=fcase(pdep,"PASSAGE_DEPENDENT",ddep,"DONOR_DEPENDENT",up,"LICENSING_CONSISTENT_UP",down,"LICENSING_CONSISTENT_DOWN",default="NO_CLEAR_LICENSING_EFFECT"),classification_rule="donor/passage rules frozen before outcomes; no cell-level P value",source_url="results/03_phase3/licensing/licensing_effect_by_donor_passage.csv|config/phase3_analysis.json");write_csv(lic,file.path(out,"licensing/licensing_ligand_classification.csv"))

# Sender-only licensing programs from the full frozen MSigDB collections.
read_gmt<-function(path,collection){z<-strsplit(readLines(path,warn=FALSE),"\\t",fixed=FALSE);rbindlist(lapply(z,function(q)data.table(gene_set=q[1],description=q[2],genes=list(unique(q[-c(1,2)])),collection=collection)))}
sets<-rbindlist(list(read_gmt("data/raw/phase2a_resources/h.all.v2026.1.Hs.symbols.gmt","HALLMARK"),read_gmt("data/raw/phase2a_resources/c2.cp.reactome.v2026.1.Hs.symbols.gmt","REACTOME"),read_gmt("data/raw/phase2a_resources/c5.go.bp.v2026.1.Hs.symbols.gmt","GO_BP")))
all_genes<-gene;sets[,idx:=lapply(genes,function(g)which(all_genes%in%g))];sets[,measured_gene_n:=lengths(idx)];sets<-sets[measured_gene_n>=15&measured_gene_n<=500];index<-sets$idx;names(index)<-sets$gene_set
cam<-function(stat){names(stat)<-gene;as.data.table(cameraPR(stat,index,inter.gene.cor=.01,sort=FALSE),keep.rownames="gene_set")}
cm<-cam(mean_effect);c1<-cam(e1);c2<-cam(e2);c22<-cam(e2p2);c25<-cam(e2p5)
prog<-merge(sets[,.(gene_set,collection,description,measured_gene_n)],cm[,.(gene_set,NGenes,Direction,PValue)],by="gene_set");prog[,BH_FDR:=p.adjust(PValue,"BH")];prog[,`:=`(donor1_direction=c1$Direction[match(gene_set,c1$gene_set)],donor2_direction=c2$Direction[match(gene_set,c2$gene_set)],donor2_p2_direction=c22$Direction[match(gene_set,c22$gene_set)],donor2_p5_direction=c25$Direction[match(gene_set,c25$gene_set)])]
prog[,program_classification:=fcase(BH_FDR<.05&Direction=="Up"&donor1_direction=="Up"&donor2_direction=="Up"&donor2_p2_direction=="Up"&donor2_p5_direction=="Up","LICENSING_PROGRAM_CONSISTENT_UP",BH_FDR<.05&Direction=="Down"&donor1_direction=="Down"&donor2_direction=="Down"&donor2_p2_direction=="Down"&donor2_p5_direction=="Down","LICENSING_PROGRAM_CONSISTENT_DOWN",Direction==donor1_direction&Direction==donor2_direction&Direction==donor2_p2_direction&Direction==donor2_p5_direction,"DIRECTIONALLY_CONSISTENT_NOT_FDR",donor1_direction!=donor2_direction|donor2_p2_direction!=donor2_p5_direction,"DONOR_OR_PASSAGE_VARIABLE",default="NO_CLEAR_LICENSING_PROGRAM")]
prog[,`:=`(method="cameraPR on mean of two donor-level effects; inter-gene correlation 0.01",interpretation="HUCMSC_INFLAMMATORY_LICENSING_ONLY_NOT_PE_THERAPEUTIC_PROGRAM",MSigDB_version="2026.1.Hs",source_url="MSigDB:2026.1.Hs|results/03_phase3/licensing/licensing_effect_by_donor.csv|config/phase3_analysis.json")];setorder(prog,BH_FDR,gene_set);write_csv(prog,file.path(out,"licensing/licensing_programs.csv"))

# Independent sender hierarchy; protein annotations remain separate columns.
hier<-merge(merge(universe,rob,by="gene",all.x=TRUE),lic,by="gene",all.x=TRUE)
hier[,sender_evidence_level:=fcase(baseline_classification=="ROBUST_BASELINE_SENDER"&licensing_classification%in%c("LICENSING_CONSISTENT_UP","LICENSING_CONSISTENT_DOWN")&retained_after_stimulation_all_strata=="YES","S1",baseline_classification=="ROBUST_BASELINE_SENDER","S2",baseline_classification%in%c("MULTIDATASET_LOW_EXPRESSION","DATASET_SPECIFIC","DONOR_VARIABLE"),"S3",default="S4")]
hier[,`:=`(transcriptomic_sender_evidence=fcase(sender_evidence_level=="S1","ROBUST_BASELINE_AND_CONSISTENT_LICENSING",sender_evidence_level=="S2","ROBUST_BASELINE_NO_CONSISTENT_LICENSING",sender_evidence_level=="S3","LIMITED_OR_VARIABLE_BASELINE",default="INSUFFICIENT_SENDER_EVIDENCE"),ligand_claim="PUTATIVE_TRANSCRIPTOMIC_LIGAND",sender_competence=ifelse(sender_evidence_level%in%c("S1","S2"),"HIGH_CONFIDENCE_SENDER_CANDIDATE","NOT_HIGH_CONFIDENCE"),licensing_responsive_ligand=ifelse(licensing_classification%in%c("LICENSING_CONSISTENT_UP","LICENSING_CONSISTENT_DOWN"),"YES","NO"),protein_evidence_interpretation="ANNOTATION_ONLY_TRANSCRIPT_DOES_NOT_PROVE_SECRETION",phase4_eligible=ifelse(sender_evidence_level%in%c("S1","S2"),"YES","NO"),source_url_phase3="results/03_phase3/baseline/baseline_sender_robustness.csv|results/03_phase3/licensing/licensing_ligand_classification.csv|config/phase3_analysis.json")]
hier[,sender_level_order:=match(sender_evidence_level,c("S1","S2","S3","S4"))];setorder(hier,sender_level_order,gene);hier[,sender_level_order:=NULL];write_csv(hier,file.path(out,"sender/sender_evidence_hierarchy.csv"))
cand<-hier[phase4_eligible=="YES"];cand[,min_dataset_median_rank:=pmin(gse182_median_rank,gse199_median_rank,na.rm=TRUE)];cand[,sender_level_order:=match(sender_evidence_level,c("S1","S2"))];setorder(cand,sender_level_order,-total_supported_donor_n,-min_dataset_median_rank,-absolute_median_donor_effect,gene);cand[,sender_level_order:=NULL];cand[,candidate_rank:=seq_len(.N)];cand[,candidate_label:="HIGH_CONFIDENCE_SENDER_CANDIDATE_NOT_THERAPEUTIC"];setcolorder(cand,c("candidate_rank","gene","sender_evidence_level","candidate_label"));write_csv(cand,file.path(out,"sender/frozen_phase4_sender_candidates.csv"))

# QC, including donor-level PCA on sender-only baseline ligand expression.
wide_cpm<-dcast(core,gene~dataset+donor_id,value.var="pseudobulk_CPM");X<-as.matrix(wide_cpm[,-1]);X[!is.finite(X)]<-0;v<-apply(log2(X+1),1,var);top<-order(v,decreasing=TRUE)[seq_len(min(500,sum(v>0)))];pc<-prcomp(t(log2(X[top,,drop=FALSE]+1)),center=TRUE,scale.=TRUE);pcs<-data.table(sample=rownames(pc$x),PC1=pc$x[,1],PC2=pc$x[,2],variance_PC1=summary(pc)$importance[2,1],variance_PC2=summary(pc)$importance[2,2]);pcs[,c("dataset","donor_id"):=tstrsplit(sample,"_",fixed=TRUE,keep=c(1,2))]
qc1<-bqc[,.(metric_group="BASELINE_DONOR",dataset,donor_id,stratum="",metric="cells",value=as.character(cells),status="OBSERVED",source_url)]
qc2<-bqc[,.(metric_group="BASELINE_DONOR",dataset,donor_id,stratum="",metric="median_cell_library_size",value=as.character(median_library_size),status="OBSERVED",source_url)]
qc3<-pcs[,.(metric_group="BASELINE_PCA",dataset,donor_id,stratum="",metric="PC1",value=as.character(PC1),status="TECHNICAL_QC_ONLY",source_url="results/03_phase3/baseline/baseline_ligand_expression_by_donor.csv")]
qc4<-pcs[,.(metric_group="BASELINE_PCA",dataset,donor_id,stratum="",metric="PC2",value=as.character(PC2),status="TECHNICAL_QC_ONLY",source_url="results/03_phase3/baseline/baseline_ligand_expression_by_donor.csv")]
qc5<-strata_reg[,.(metric_group="LICENSING_STRATUM",dataset="GSE117837",donor_id,stratum=stratum_id,metric="untreated_cells",value=as.character(UNTREATED),status=valid_within_stratum_contrast,source_url)]
qc6<-strata_reg[,.(metric_group="LICENSING_STRATUM",dataset="GSE117837",donor_id,stratum=stratum_id,metric="stimulated_cells",value=as.character(IFNG_TNFA_STIMULATED),status=valid_within_stratum_contrast,source_url)]
qc7<-data.table(metric_group="CROSS_DATASET",dataset="GSE182158_vs_GSE199071",donor_id="",stratum="",metric="spearman_ligand_rank",value=as.character(rho),status="DESCRIPTIVE",source_url="results/03_phase3/baseline/cross_dataset_sender_concordance.csv")
qc8<-data.table(metric_group="STRUCTURAL_CONFOUNDING",dataset=c("GSE182158","GSE199071","GSE117837","GSE117837"),donor_id="",stratum="",metric=c("source_protocol_confounding","donor_passage_sex_confounding","donor_passage_structure","treatment_within_stratum_positivity"),value=c("tissue source cannot be separated from collection/culture protocol","HUCMSC1=P3/female; HUCMSC2-4=P6/male","Donor1 P5 only; Donor2 P0/P2/P5","valid D1P5,D2P2,D2P5; D2P0 untreated-only"),status=c("OPEN_CONTEXT_ONLY","OPEN","MODELED_BY_DONOR_SUMMARY","THREE_VALID_ONE_INVALID"),source_url="config/phase3_analysis.json")
qcs<-rbindlist(list(qc1,qc2,qc3,qc4,qc5,qc6,qc7,qc8),fill=TRUE);write_csv(qcs,file.path(out,"qc/phase3_qc_summary.csv"))

class_counts<-hier[,.N,by=sender_evidence_level];base_counts<-rob[,.N,by=baseline_classification];lic_counts<-lic[,.N,by=licensing_classification]
risks<-data.table(risk_id=paste0("P3-",sprintf("%03d",1:10)),severity=c("HIGH","HIGH","MEDIUM","MEDIUM","HIGH","MEDIUM","MEDIUM","MEDIUM","MEDIUM","HIGH"),status=c("OPEN","OPEN","OPEN","OPEN","MITIGATED_WORDING","MITIGATED","OPEN","FROZEN","MITIGATED","MITIGATED"),risk=c("Cross-study donor overlap cannot be independently excluded","Only two independent donors support licensing generalization","GSE199071 donor is partially confounded with passage and sex","GSE182158 source context is confounded with protocol and tissue collection","Transcript expression does not prove secretion or protein abundance","Cells and passages could be mistaken for biological replication","GSE117837 GEO GSM counts differ from Series design summary by one cell in two P5 groups","Ligand and program database versions can change","Cross-platform expression scales are not directly comparable","Receiver information could leak into sender selection"),impact=c("Eight hUCMSC donors are study-labelled independent, not genomically proven unique","No conventional P value establishes a general licensing response","Baseline donor variability can partly reflect passage/sex","UC-versus-other differences are context, not causal origin effects","Candidates are putative transcriptomic ligands only","Inflated replication and false precision","Published 52/59 and 50/50 P5 summary differs from GSM-derived 52/58 and 51/50","Future database releases may alter membership","Raw CPM values cannot be pooled across studies","Circular therapeutic prioritization"),mitigation=c("Preserve dataset-specific independence groups and overlap flag","Require direction and passage consistency; cap gate at restrictions","Use donor detection/ranks; no causal passage/sex model","Do not require UC specificity and report source delta descriptively","Keep protein annotation separate and use non-secretory wording","Donor-level baseline and donor-first passage summaries only","Use auditable GSM labels and retain discrepancy flag","Freeze files by SHA-256 and version","Use within-dataset ranks and detection rules","Source-code validation rejects results/02 paths and PE compatibility analyses"),observed_phase3_result=c("UNRESOLVED","two licensing donors; three valid donor-passage strata","OPEN","source context never changes robust class", "all candidates remain transcript-level", "no cell-level P values generated", "D1P5 52/58 and D2P5 51/50 from GSM labels", "NicheNet 2021-12-21 plus OmniPath 2026-08-10 and MSigDB 2026.1.Hs",sprintf("cross-dataset rank rho %.3f",rho),"sender scripts read no results/02 receiver path"),source_url="config/phase3_analysis.json|docs/PHASE3_INDEPENDENT_SENDER_ANALYSIS_PLAN.md");write_csv(risks,file.path(out,"qc/phase3_risk_flags.csv"))

metrics<-rbindlist(list(data.table(metric="frozen_ligand_universe_n",value=nrow(universe)),data.table(metric="detectably_expressed_any_core_donor_n",value=rob[gse182_low_detected_donor_n+gse199_low_detected_donor_n>=1,.N]),data.table(metric="robust_baseline_sender_n",value=rob[baseline_classification=="ROBUST_BASELINE_SENDER",.N]),data.table(metric="licensing_consistent_up_n",value=lic[licensing_classification=="LICENSING_CONSISTENT_UP",.N]),data.table(metric="licensing_consistent_down_n",value=lic[licensing_classification=="LICENSING_CONSISTENT_DOWN",.N]),data.table(metric="passage_dependent_n",value=lic[licensing_classification=="PASSAGE_DEPENDENT",.N]),data.table(metric="donor_dependent_n",value=lic[licensing_classification=="DONOR_DEPENDENT",.N]),data.table(metric="phase4_candidate_n",value=nrow(cand)),data.table(metric="S1_n",value=hier[sender_evidence_level=="S1",.N]),data.table(metric="S2_n",value=hier[sender_evidence_level=="S2",.N]),data.table(metric="S3_n",value=hier[sender_evidence_level=="S3",.N]),data.table(metric="S4_n",value=hier[sender_evidence_level=="S4",.N]),data.table(metric="consistent_licensing_program_n",value=prog[program_classification%in%c("LICENSING_PROGRAM_CONSISTENT_UP","LICENSING_PROGRAM_CONSISTENT_DOWN"),.N]),data.table(metric="cross_dataset_rank_rho",value=rho)))
write_csv(metrics,file.path(out,"phase3_metrics.csv"));si<-sub("[[:space:]]+$","",capture.output(sessionInfo()));writeLines(si,file.path(out,"phase3_session_info.txt"));message("Phase 3 sender analysis complete")
