#!/usr/bin/env Rscript

suppressPackageStartupMessages({library(data.table);library(limma);library(metafor)})
args<-commandArgs(trailingOnly=TRUE);root<-if(length(args))normalizePath(args[1],winslash="/",mustWork=TRUE)else normalizePath(".",winslash="/")
setwd(root);set.seed(20260810)
out<-"results/02_phase2b";for(d in c("scores","meta","robustness","evidence","figures"))dir.create(file.path(out,d),recursive=TRUE,showWarnings=FALSE)
write_csv<-function(x,p)fwrite(x,p,na="",quote=TRUE)
cohorts<-c("GSE75010_BIOBANK","GSE30186","GSE10588","GSE24129","GSE25906","GSE43942")
primary_formulas<-c(GSE75010_BIOBANK="~ disease",GSE30186="~ disease",GSE10588="~ disease",GSE24129="~ disease",GSE25906="~ disease + batch",GSE43942="~ disease")
expected_sign<-function(x)ifelse(x=="UP_IN_PE_PROGRAM",1,-1)

read_gene_matrix<-function(path){d<-read.delim(gzfile(path),check.names=FALSE,stringsAsFactors=FALSE);g<-d[[1]];m<-as.matrix(d[,-1,drop=FALSE]);storage.mode(m)<-"double";rownames(m)<-g;stopifnot(!anyDuplicated(g),!anyDuplicated(colnames(m)));m}
ga_numeric<-function(x){z<-suppressWarnings(as.numeric(x));w<-grepl("^[0-9]+w\\+[0-9]+d$",x);if(any(w)){b<-strsplit(x[w],"w\\+|d");z[w]<-vapply(b,function(q)as.numeric(q[1])+as.numeric(q[2])/7,numeric(1))};z}
make_data<-function(md)data.frame(disease=factor(md$`PE/control`,levels=c("CONTROL","PE")),GA_c=ga_numeric(md$GA)-mean(ga_numeric(md$GA),na.rm=TRUE),fetal_sex=factor(md$`fetal sex`,levels=c("F","M")),batch=factor(md$batch,levels=c("A","B")),labor=factor(md$labor,levels=c("spontaneous","induced")),check.names=FALSE)
fit_score<-function(score,md,formula_text){dat<-make_data(md);need<-all.vars(as.formula(formula_text));ok<-complete.cases(dat[,need,drop=FALSE])&is.finite(score);dat<-dat[ok,,drop=FALSE];y<-score[ok];X<-model.matrix(as.formula(formula_text),dat);stopifnot(qr(X)$rank==ncol(X),"diseasePE"%in%colnames(X),nrow(X)>ncol(X));fit<-lm.fit(X,y);df<-nrow(X)-ncol(X);s2<-sum(fit$residuals^2)/df;vc<-chol2inv(fit$qr$qr[seq_len(ncol(X)),seq_len(ncol(X)),drop=FALSE])*s2;j<-match("diseasePE",colnames(X));beta<-fit$coefficients[j];se<-sqrt(vc[j,j]);t<-beta/se;p<-2*pt(-abs(t),df);crit<-qt(.975,df);list(beta=beta,se=se,ci_l=beta-crit*se,ci_u=beta+crit*se,t=t,p=p,df=df,n_PE=sum(dat$disease=="PE"),n_control=sum(dat$disease=="CONTROL"),complete_n=nrow(X),rank=qr(X)$rank,condition=kappa(X))}

hyp<-fread(file.path(out,"hypotheses/frozen_phase2b_gene_sets.csv"));mods<-fread(file.path(out,"hypotheses/frozen_phase2b_modules.csv"))
stopifnot(nrow(hyp)==19,uniqueN(hyp$program_module)==10,!"PROGRAM_MODULE_08"%in%hyp$program_module)
hyp[,genes:=strsplit(original_gene_membership,";",fixed=TRUE)]
freeze<-fread("results/01_phase1a/bulk_sample_freeze.csv",check.names=FALSE);reg<-fread("results/01_phase1a1/formal_phase1b_matrix_registry.csv")
paths<-setNames(reg$gene_matrix_path,reg$dataset);sources<-setNames(reg$source,reg$dataset)
matrices<-list();metadata<-list();score_cache<-list();coverage_rows<-list();model_rows<-list()
for(cohort in cohorts){
  message("Rank-scoring ",cohort)
  m<-read_gene_matrix(paths[[cohort]]);md<-freeze[dataset==cohort & include_phase1b=="YES" & `PE/control`%in%c("PE","CONTROL")]
  sam<-intersect(colnames(m),md$`GSM/sample ID`);md<-md[match(sam,`GSM/sample ID`)];m<-m[,sam,drop=FALSE];stopifnot(ncol(m)==nrow(md),!anyNA(md$`GSM/sample ID`))
  ranks<-apply(m,2,rank,ties.method="average");frac<-(ranks-1)/(nrow(m)-1);rownames(frac)<-rownames(m);colnames(frac)<-colnames(m)
  matrices[[cohort]]<-m;metadata[[cohort]]<-md
  for(i in seq_len(nrow(hyp))){
    genes<-hyp$genes[[i]];meas<-intersect(genes,rownames(frac));n<-length(meas);prop<-n/length(genes);estim<-n>=15&&prop>=.60
    score<-if(estim)colMeans(frac[meas,,drop=FALSE])else rep(NA_real_,ncol(frac));sdv<-sd(score,na.rm=TRUE);if(!is.finite(sdv)||sdv==0)estim<-FALSE
    z<-if(estim)as.numeric(scale(score))else rep(NA_real_,length(score));names(z)<-colnames(frac);score_cache[[paste(cohort,hyp$hypothesis_id[i],sep="|")]]<-z
    coverage_rows[[length(coverage_rows)+1]]<-data.table(cohort=cohort,hypothesis_id=hyp$hypothesis_id[i],program_module=hyp$program_module[i],gene_set=hyp$gene_set[i],celltype_origin=hyp$celltype_origin[i],scRNA_direction=hyp$scRNA_direction[i],original_gene_n=length(genes),measured_gene_n=n,membership_coverage=prop,minimum_gene_rule=15L,minimum_fraction_rule=.60,estimable=ifelse(estim,"YES","NO"),missing_genes=paste(setdiff(genes,meas),collapse=";"),matrix_path=paths[[cohort]],source_url=paste0(sources[[cohort]],"|MSigDB:2026.1.Hs"))
    if(estim){f<-fit_score(z,md,primary_formulas[[cohort]]);disease<-md$`PE/control`;model_rows[[length(model_rows)+1]]<-data.table(cohort=cohort,hypothesis_id=hyp$hypothesis_id[i],program_module=hyp$program_module[i],gene_set=hyp$gene_set[i],celltype_origin=hyp$celltype_origin[i],scRNA_direction=hyp$scRNA_direction[i],model_formula=primary_formulas[[cohort]],beta_disease=f$beta,SE=f$se,CI_lower=f$ci_l,CI_upper=f$ci_u,t_statistic=f$t,raw_P=f$p,residual_df=f$df,n_PE=f$n_PE,n_control=f$n_control,measured_gene_n=n,membership_coverage=prop,score_mean_PE=mean(z[disease=="PE"]),score_mean_control=mean(z[disease=="CONTROL"]),observed_direction=ifelse(f$beta>=0,"UP_IN_PE","DOWN_IN_PE"),agrees_scRNA_direction=ifelse(sign(f$beta)==expected_sign(hyp$scRNA_direction[i]),"YES","NO"),score_method="mean_fractional_rank_then_within_cohort_z",source_url=paste0(sources[[cohort]],"|config/phase2b_analysis.json"))}
  }
  rm(ranks,frac);invisible(gc())
}
coverage<-rbindlist(coverage_rows);models<-rbindlist(model_rows);models[,BH_FDR_within_cohort:=p.adjust(raw_P,"BH",n=19),by=cohort]
setorder(coverage,hypothesis_id,cohort);setorder(models,hypothesis_id,cohort)
write_csv(coverage,file.path(out,"scores/program_gene_coverage.csv"));write_csv(models,file.path(out,"scores/cohort_program_scores_summary.csv"))

# Same Phase 1B REML point estimator and conservative modified Knapp-Hartung inference.
reml_score<-function(y,v,tau){w<-1/(v+tau);sw<-sum(w);mu<-sum(w*y)/sw;.5*(sum(w^2*(y-mu)^2)-(sw-sum(w^2)/sw))}
meta_one<-function(y,se,min_k=4){ok<-is.finite(y)&is.finite(se)&se>0;y<-y[ok];se<-se[ok];k<-length(y);if(k<min_k)return(NULL);v<-se^2;s0<-reml_score(y,v,0);tau<-0;if(is.finite(s0)&&s0>0){lo<-0;hi<-max(var(y),mean(v),1e-4)*10+1e-4;while(reml_score(y,v,hi)>0)hi<-hi*4;for(i in 1:80){mid<-(lo+hi)/2;if(reml_score(y,v,mid)>0)lo<-mid else hi<-mid};tau<-(lo+hi)/2};w<-1/(v+tau);mu<-sum(w*y)/sum(w);qe<-sum(w*(y-mu)^2);scale<-max(1,qe/(k-1));pse<-sqrt(scale/sum(w));stat<-mu/pse;df<-k-1;p<-2*pt(-abs(stat),df);crit<-qt(.975,df);w0<-1/v;mu0<-sum(w0*y)/sum(w0);q<-sum(w0*(y-mu0)^2);i2<-if(q>0)max(0,(q-(k-1))/q)*100 else 0;list(k=k,effect=mu,se=pse,ci_l=mu-crit*pse,ci_u=mu+crit*pse,stat=stat,df=df,p=p,tau=tau,i2=i2,q=q,qp=pchisq(q,k-1,lower.tail=FALSE),keep=ok)}
meta_rows<-list();loco_rows<-list()
for(i in seq_len(nrow(hyp))){
  d<-models[hypothesis_id==hyp$hypothesis_id[i]];y<-setNames(d$beta_disease,d$cohort);s<-setNames(d$SE,d$cohort);y<-y[cohorts];s<-s[cohorts];mf<-meta_one(y,s,4);if(is.null(mf))next
  exp<-expected_sign(hyp$scRNA_direction[i]);prop<-mean(sign(y[is.finite(y)])==exp);loco_effect<-rep(NA_real_,length(cohorts));names(loco_effect)<-cohorts
  for(omit in cohorts){yy<-y;ss<-s;yy[omit]<-NA;ss[omit]<-NA;lf<-meta_one(yy,ss,3);if(!is.null(lf)){loco_effect[omit]<-lf$effect;loco_rows[[length(loco_rows)+1]]<-data.table(hypothesis_id=hyp$hypothesis_id[i],program_module=hyp$program_module[i],gene_set=hyp$gene_set[i],scRNA_direction=hyp$scRNA_direction[i],omitted_cohort=omit,remaining_cohort_n=lf$k,summary_standardized_beta=lf$effect,SE=lf$se,CI_lower=lf$ci_l,CI_upper=lf$ci_u,raw_P=lf$p,I2=lf$i2,direction=ifelse(lf$effect>=0,"UP_IN_PE","DOWN_IN_PE"),expected_direction_retained=ifelse(sign(lf$effect)==exp,"YES","NO"),source_url="six frozen program-score models|config/phase2b_analysis.json")}}
  meta_rows[[i]]<-data.table(hypothesis_id=hyp$hypothesis_id[i],program_module=hyp$program_module[i],module_label=hyp$module_label[i],gene_set=hyp$gene_set[i],celltype_origin=hyp$celltype_origin[i],scRNA_direction=hyp$scRNA_direction[i],k_cohorts=mf$k,summary_standardized_beta=mf$effect,SE=mf$se,CI_lower=mf$ci_l,CI_upper=mf$ci_u,test_statistic=mf$stat,test_df=mf$df,raw_meta_P=mf$p,tau2=mf$tau,I2=mf$i2,Cochran_Q=mf$q,Q_P=mf$qp,expected_direction_cohort_proportion=prop,all_valid_LOCO_expected_direction=ifelse(all(sign(loco_effect[is.finite(loco_effect)])==exp),"YES","NO"),GSE75010_LOCO_effect=loco_effect["GSE75010_BIOBANK"],cohort_effects=paste(paste(names(y)[is.finite(y)],format(y[is.finite(y)],digits=6),sep="="),collapse=";"),meta_method="REML_MODIFIED_KNHA_T",source_url="six frozen program-score models|config/phase2b_analysis.json")
}
meta<-rbindlist(meta_rows);meta[,BH_FDR:=p.adjust(raw_meta_P,"BH",n=19)]
loco<-rbindlist(loco_rows);loco[,BH_FDR:=p.adjust(raw_P,"BH",n=19),by=omitted_cohort]
meta[,classification:=fcase(k_cohorts>=4&BH_FDR<.05&sign(summary_standardized_beta)==expected_sign(scRNA_direction)&expected_direction_cohort_proportion>=.75&I2<=60&all_valid_LOCO_expected_direction=="YES","BULK_ROBUST_SUPPORT",k_cohorts>=4&BH_FDR<.05&sign(summary_standardized_beta)==expected_sign(scRNA_direction)&expected_direction_cohort_proportion>=.75&I2>60,"BULK_HETEROGENEOUS_SUPPORT",k_cohorts>=4&sign(summary_standardized_beta)==expected_sign(scRNA_direction)&expected_direction_cohort_proportion>=.75,"BULK_DIRECTIONAL_SUPPORT",default="NOT_BULK_SUPPORTED")]
meta[,GSE75010_LOCO_P:=loco[omitted_cohort=="GSE75010_BIOBANK",raw_P][match(hypothesis_id,loco[omitted_cohort=="GSE75010_BIOBANK",hypothesis_id])]]
meta[,GSE75010_driver:=ifelse(sign(GSE75010_LOCO_effect)!=expected_sign(scRNA_direction)|(classification=="BULK_ROBUST_SUPPORT"&GSE75010_LOCO_P>=.05),"YES","NO")]
setorder(meta,hypothesis_id);setorder(loco,hypothesis_id,omitted_cohort)
write_csv(meta,file.path(out,"meta/program_gene_set_meta_analysis.csv"));write_csv(loco,file.path(out,"robustness/program_leave_one_cohort_out.csv"))

# Frozen module aggregation only; no pooled module gene union.
module_rows<-list()
for(i in seq_len(nrow(mods))){d<-meta[program_module==mods$program_module[i]];req<-mods$required_robust_or_directional_n[i];rob<-sum(d$classification=="BULK_ROBUST_SUPPORT");dirn<-sum(d$classification=="BULK_DIRECTIONAL_SUPPORT");het<-sum(d$classification=="BULK_HETEROGENEOUS_SUPPORT");opp<-sum(sign(d$summary_standardized_beta)!=expected_sign(d$scRNA_direction));est<-nrow(d);cl<-if(rob>=req)"BULK_MODULE_SUPPORTED"else if(dirn>=req)"BULK_MODULE_DIRECTIONAL"else if(est>0&&opp/est>=.40)"BULK_MODULE_DISCORDANT"else "NOT_BULK_SUPPORTED";module_rows[[i]]<-data.table(program_module=mods$program_module[i],module_label=mods$module_label[i],celltype_origin=mods$celltype_origin[i],scRNA_direction=mods$scRNA_direction[i],constituent_gene_set_n=mods$constituent_gene_set_n[i],estimable_constituent_n=est,required_support_n=req,robust_support_n=rob,directional_support_n=dirn,heterogeneous_support_n=het,not_supported_n=sum(d$classification=="NOT_BULK_SUPPORTED"),opposite_meta_direction_n=opp,module_classification=cl,representative_hypothesis_id=d[order(gene_set)]$hypothesis_id[1],representative_gene_set=d[order(gene_set)]$gene_set[1],representative_rule="lexicographically first constituent",celltype_claim="NOT_VALIDATED_BY_BULK_TISSUE_LEVEL_PROGRAM_ONLY",source_url="results/02_phase2b/meta/program_gene_set_meta_analysis.csv|config/phase2b_analysis.json")}
module_validation<-rbindlist(module_rows);write_csv(module_validation,file.path(out,"meta/program_module_validation.csv"))

# cameraPR on frozen Phase 1B gene moderated statistics only.
cam_rows<-list()
for(coh in cohorts){de<-fread(file.path("results/01_phase1b/cohort_DE",paste0(coh,"_DE.csv")));stat<-setNames(de$t_statistic,de$gene);idx<-lapply(seq_len(nrow(hyp)),function(i)intersect(hyp$genes[[i]],names(stat)));names(idx)<-hyp$hypothesis_id;valid<-vapply(seq_len(nrow(hyp)),function(i)coverage[cohort==coh & hypothesis_id==hyp$hypothesis_id[i],estimable][1]=="YES",logical(1));cp<-as.data.table(cameraPR(stat,idx[valid],inter.gene.cor=.01,sort=FALSE),keep.rownames="hypothesis_id");cp<-merge(cp,hyp[,.(hypothesis_id,program_module,gene_set,celltype_origin,scRNA_direction)],by="hypothesis_id");cp[,`:=`(cohort=coh,camera_direction=ifelse(Direction=="Up","UP_IN_PE","DOWN_IN_PE"),camera_P=PValue,camera_BH_FDR=p.adjust(PValue,"BH",n=19),expected_direction_agreement=ifelse(ifelse(Direction=="Up",1,-1)==expected_sign(scRNA_direction),"YES","NO"),label="METHOD_CONCORDANCE_SENSITIVITY",source_url=paste0("results/01_phase1b/cohort_DE/",coh,"_DE.csv|MSigDB:2026.1.Hs"))];pm<-models[cohort==coh,.(hypothesis_id,primary_beta=beta_disease,primary_direction=observed_direction)];cp<-merge(cp,pm,by="hypothesis_id");cp[,primary_camera_direction_agreement:=ifelse(primary_direction==camera_direction,"YES","NO")];cam_rows[[coh]]<-cp}
camera<-rbindlist(cam_rows,fill=TRUE);setorder(camera,hypothesis_id,cohort);write_csv(camera,file.path(out,"robustness/cameraPR_method_concordance.csv"))

# Biological-covariate sensitivities; adjusted effects never enter primary meta-analysis.
specs<-list(GSE75010_BIOBANK_GA_SEX=c("GSE75010_BIOBANK","~ disease + GA_c + fetal_sex"),GSE25906_GA_SEX=c("GSE25906","~ disease + batch + GA_c + fetal_sex"),GSE25906_GA_SEX_LABOR=c("GSE25906","~ disease + batch + GA_c + fetal_sex + labor"));covrows<-list()
for(id in names(specs)){coh<-specs[[id]][1];form<-specs[[id]][2];md<-metadata[[coh]];for(i in seq_len(nrow(hyp))){z<-score_cache[[paste(coh,hyp$hypothesis_id[i],sep="|")]];if(!any(is.finite(z)))next;adj<-fit_score(z,md,form);pri<-models[cohort==coh&hypothesis_id==hyp$hypothesis_id[i]][1];att<-if(pri$beta_disease!=0)adj$beta/pri$beta_disease else NA_real_;rel<-abs(adj$beta-pri$beta_disease)/max(abs(pri$beta_disease),.05);flag<-sign(adj$beta)!=sign(pri$beta_disease)||is.finite(att)&&abs(att)<.5||rel>.25;covrows[[length(covrows)+1]]<-data.table(cohort=coh,model_id=id,hypothesis_id=hyp$hypothesis_id[i],program_module=hyp$program_module[i],gene_set=hyp$gene_set[i],scRNA_direction=hyp$scRNA_direction[i],adjusted_formula=form,primary_beta=pri$beta_disease,adjusted_beta=adj$beta,adjusted_SE=adj$se,adjusted_P=adj$p,sign_concordant=ifelse(sign(adj$beta)==sign(pri$beta_disease),"YES","NO"),attenuation_ratio=att,relative_change=rel,material_change_flag=ifelse(flag,"YES","NO"),complete_case_n=adj$complete_n,source_url=paste0(sources[[coh]],"|config/phase2b_analysis.json"))}}
covsens<-rbindlist(covrows);write_csv(covsens,file.path(out,"robustness/program_covariate_sensitivity.csv"))

# Receiver evidence keeps cellular localization and tissue-level validation as separate columns.
old<-fread("results/02_phase2a2/evidence/receiver_module_evidence_hierarchy.csv");if("bulk_evidence_used"%in%names(old))setnames(old,"bulk_evidence_used","phase2a2_bulk_evidence_used_legacy");ev<-merge(old,module_validation[,.(program_module,bulk_module_classification=module_classification,bulk_robust_constituent_n=robust_support_n,bulk_directional_constituent_n=directional_support_n,bulk_heterogeneous_constituent_n=heterogeneous_support_n)],by="program_module",all.x=TRUE)
ev[,`:=`(CORRECTED_ADMATI_SUPPORT=corrected_module_status,EXTERNAL_SCRNA_SUPPORT=fcase(evidence_level=="LEVEL_A","YANG_LOPE_DIRECTIONAL_SUPPORT",evidence_level=="LEVEL_B","NOT_EVALUABLE",default="DIRECTIONALLY_DISCORDANT"),INDEPENDENT_BULK_PROGRAM_SUPPORT=ifelse(program_module=="PROGRAM_MODULE_08","NOT_TESTED_HOLD_EXTERNAL_DISCORDANCE",bulk_module_classification),bulk_validation_scope="PLACENTAL_TISSUE_LEVEL_PROGRAM_ONLY",celltype_localization_claim="DEPENDENT_ON_SINGLE_CELL_EVIDENCE_NOT_VALIDATED_BY_BULK",phase3_candidate=ifelse(program_module!="PROGRAM_MODULE_08"&bulk_module_classification%in%c("BULK_MODULE_SUPPORTED","BULK_MODULE_DIRECTIONAL"),"YES_WITH_EVIDENCE_QUALIFIERS","NO"),source_url_phase2b="results/02_phase2b/meta/program_module_validation.csv|config/phase2b_analysis.json")]
write_csv(ev,file.path(out,"evidence/updated_receiver_evidence_hierarchy.csv"))

risks<-data.table(risk_id=paste0("P2B-",sprintf("%03d",1:8)),severity=c("HIGH","HIGH","MEDIUM","HIGH","HIGH","MEDIUM","MEDIUM","HIGH"),status=c("FROZEN_VISIBLE","MITIGATED","OPEN","OPEN","OPEN","MITIGATED_FOR_CURRENT_FAMILY","OBSERVED_LIMITED","MITIGATED"),risk=c("Phase 1B strict gene-level meta-analysis yielded zero STABLE genes","Bulk tissue cannot validate cell-type origin","Overlapping constituent sets are statistically dependent","Gestational-age/FGR/subtype heterogeneity across cohorts","Small k random-effects uncertainty","Platform coverage differs by historical assay","GSE75010 BioBank may dominate tissue-level effects","Module 08 external scRNA discordance"),impact=c("Program validation must not be presented as rescue of individual genes","Any Hofbauer/SCT/stromal label remains a single-cell localization claim","Nineteen rows do not equal nineteen independent mechanisms","Tissue-level effects can mix disease subtype and clinical composition","Six cohorts limit heterogeneity estimation and LOCO precision","Non-estimability is platform absence, not biological evidence","Large cohort can influence precision and full meta significance","Discordant hypothesis could contaminate validation family"),mitigation=c("State STABLE=0 in report and evidence table","Use tissue-level program wording only","Aggregate decisions at frozen module level","Retain heterogeneity and covariate sensitivity reporting","Modified Knapp-Hartung and LOCO","Freeze >=15 and >=60% coverage","Explicit GSE75010 LOCO driver flag","Exclude Module 08 before outcomes"),observed_phase2b_result=c("Phase 1B STABLE remains 0; Phase 2B reports program-level evidence only","All bulk classifications explicitly use placental tissue-level wording","19 frozen rows represent 16 unique gene sets across 10 modules","GSE25906 adjusted-score sensitivities materially changed 14/19 GA-sex and 16/19 GA-sex-labor effects","No constituent met robust support; minimum family BH FDR was 0.1429","All 19 hypotheses were estimable in all six cohorts under the frozen coverage rule","Five unsupported hypotheses flipped expected direction when BioBank was omitted; none of nine directionally supported hypotheses did","Module 08 was absent from the 19-test family and remains held"),source_url="config/phase2b_analysis.json|docs/PHASE2B_STATISTICAL_ANALYSIS_PLAN.md")
write_csv(risks,file.path(out,"evidence/phase2b_risk_flags.csv"))

metrics<-data.table(metric=c("frozen_hypothesis_n","estimable_ge4_n","robust_n","directional_n","heterogeneous_n","not_supported_n","module_supported_n","module_directional_n","module_discordant_n","module_not_supported_n","GSE75010_driver_hypothesis_n","camera_primary_direction_agreement_proportion","covariate_material_change_pair_n"),value=c(nrow(hyp),sum(meta$k_cohorts>=4),sum(meta$classification=="BULK_ROBUST_SUPPORT"),sum(meta$classification=="BULK_DIRECTIONAL_SUPPORT"),sum(meta$classification=="BULK_HETEROGENEOUS_SUPPORT"),sum(meta$classification=="NOT_BULK_SUPPORTED"),sum(module_validation$module_classification=="BULK_MODULE_SUPPORTED"),sum(module_validation$module_classification=="BULK_MODULE_DIRECTIONAL"),sum(module_validation$module_classification=="BULK_MODULE_DISCORDANT"),sum(module_validation$module_classification=="NOT_BULK_SUPPORTED"),sum(meta$GSE75010_driver=="YES"),mean(camera$primary_camera_direction_agreement=="YES"),sum(covsens$material_change_flag=="YES")))
write_csv(metrics,file.path(out,"phase2b_metrics.csv"));si<-sub("[[:space:]]+$","",capture.output(sessionInfo()));writeLines(si,file.path(out,"phase2b_session_info.txt"));message("Phase 2B primary analysis complete")
